/* claucia_logico: */

CREATE TABLE INTITUTION (
    name VARCHAR(255) PRIMARY KEY
);

CREATE TABLE PROFESSIONAL (
    coren VARCHAR(255) PRIMARY KEY,
    password VARCHAR(255),
    name VARCHAR(255),
    photo VARCHAR(255)
);

CREATE TABLE PATIENT (
    id INT PRIMARY KEY,
    name VARCHAR(255),
    date_of_birth DATE,
    sex CHAR(1),
    photo VARCHAR(255)
);

CREATE TABLE WOUND (
    id INT PRIMARY KEY,
    location VARCHAR(255),
    origin VARCHAR(255),
    FK_PATIENT_id INT
);

CREATE TABLE SAMPLE (
    id INT PRIMARY KEY,
    photo VARCHAR(255),
    ai_classification INT,
    professional_classification INT,
    height FLOAT,
    width FLOAT,
    date TIMESTAMP,
    FK_WOUND_id INT,
    FK_PROFESSIONAL_coren VARCHAR(255)
);

CREATE TABLE works (
    fk_INTITUTION_name VARCHAR(255),
    fk_PROFESSIONAL_coren VARCHAR(255)
);
 
ALTER TABLE WOUND ADD CONSTRAINT FK_WOUND_2
    FOREIGN KEY (FK_PATIENT_id)
    REFERENCES PATIENT (id)
    ON DELETE CASCADE;
 
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_2
    FOREIGN KEY (FK_WOUND_id)
    REFERENCES WOUND (id)
    ON DELETE CASCADE;
 
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_3
    FOREIGN KEY (FK_PROFESSIONAL_coren)
    REFERENCES PROFESSIONAL (coren)
    ON DELETE CASCADE;
 
ALTER TABLE works ADD CONSTRAINT FK_works_1
    FOREIGN KEY (fk_INTITUTION_name)
    REFERENCES INTITUTION (name)
    ON DELETE RESTRICT;
 
ALTER TABLE works ADD CONSTRAINT FK_works_2
    FOREIGN KEY (fk_PROFESSIONAL_coren)
    REFERENCES PROFESSIONAL (coren)
    ON DELETE SET NULL;